name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  golangci:
    name: lint

    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43
